/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author dmytro.prytula prituladima@gmail.com
 */

#include <iostream>
#include <fstream>

#include <iostream>

class Task1000 {
public:
    void solve(std::istream &in, std::ostream &out) {
        int a, b;
        in >> a >> b;
        out << a + b;
    }
};

int main() {
    std::ios::sync_with_stdio(false);
	Task1000 solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
